server:
  port: 3000

pig:
  auth:
    clientId: ENC(Ho5VxMWMMIzfIEE8/WxVzA==)
    clientSecret: ENC(Ho5VxMWMMIzfIEE8/WxVzA==)
    scope: server
    
ribbon:
  Httpclient:
    enable: false
  OkHttp:
    enable: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
  
feign:
  okhttp:
    enable: true
  httpclient:
    enable: false
    
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
#加密参数
jasypt:
  encryptor:
    password: lengleng
    
logging:
  config: classpath:logback.xml

